### PR TITLE
Chainable immutable lazy sequence by returning new Rando instance

### PR DESCRIPTION
**Pull request by Nudelsieb**
Combine the power of lazy sequences with our home-baked API and maintain purity. That means that we don't do `this._numbers = this._numbers.filter(func)`, which can be considered impure. Instead the functor (`Rando`) receives the result of the last filter call which in turn is a new immutable sequence from a functional point of view.

Because we don't mutate Rando's inner state (re-assign `_numbers`) and always return a new instance of `Rando` with it's own state (functor) we could assign the result of a computation of `Rando` like `const filterResult = Rando.range(1, 10).filter(filters something)` and use it like `filterResult.filter(filter something on top of this result)` as often as we like, or create new results from that, which in turn can be re-used. The point is that we could do that already but not without mutating the innser state (_numbers) of our `Rando` instance. When we save this instance/state and run more than one filter on it we would not get the same results as if we would always return a new instance in each filter call. The new approach makes this safe though.

Example:
```
const allEvenNumbers = Rando.range(1, 10).even(); // ORIGINAL state

const squared = allEvenNumbers.square(); // creates new state from ORIGINAL state
const randomNumber = squared.random(); // single number

const prime = allEvenNumbers.prime(); // creates new state from ORIGINAL state
const listOfNumbers = prime.numbers(); // list of numbers/array
```

### CODE REVIEW

**Comment by Nudelsieb** [comment]
Next optimisation steps could be `cacheResult()` of `_.memoize()` to reduce call of `map()`.

https://facebook.github.io/immutable-js/docs/#/Seq/cacheResult

**Comment by Nudelsieb** [comment]
@myabc @mmrwoods can we merge this or is there a disagreement of its usefulness?

**Comment by mmrwoods** [comment]
@Nudelsieb I really like that this allows an instance of Rando to be assigned to a variable, and be used as the basis for further number generation. This definitely makes Rando more useful :-)

Having said that, I don't think the commit messages do these changes justice. The first one says it makes class a functor, but there's nothing explaining why. The second adds a map() method because functors should have a map method, but that kind of "just because" commit message isn't very helpful.

As the commit messages don't explain why the class instance must be a functor in order to support this idea of using an instance of Rando for further number generation, it makes me question whether it actually must be a functor at all. I don't know the answer to this question, but it's a question I probably wouldn't ask if the commit messages explained how a functor achieves this goal, and why a functor is the best way to achieve this goal.

**Comment by mmrwoods** [comment]
@Nudelsieb btw, I am aware that there are other benefits to using a functor. Being able to treat an instance of Rando as something that's iterable is really quite handy, but again, the commit messages don't explain this.

**Comment by Nudelsieb** [comment]
@mmrwoods I agree that the CM's lack why a functor is useful. They should have been more descriptive.

On the other hand I don't think I should explain why a functor needs a map method. The rules are available for everyone to be searched and found on the WWW.

I am currently not aware of any other pattern to achieve the same goal other than using a functor in a clean way. you have to return a new instance to represent a unique state.

I will amend these CM's in due time and will try to improve them in the future :).

**Comment by mmrwoods** [comment]
@Nudelsieb I agree that you don't need to explain why a functor needs a map method. A functor is not a functor unless it's mappable, which is js means it has a map method (I think, correct me if I'm wrong on that).

The confusion for me arises because your first commit seems to achieve the goal of returning a new instance to allow an instance of Rando with some filters applied to be used as the basis for further filtering. As it does this without adding a map method, and a functor needs a map method, the goal is achieved without actually using a functor, right?

If a functor needs a map method, then it's the second commit that makes Rando a functor, which is useful, but not necessary to achieve the goal of this PR. I'm not saying I don't think it should be added, just that it seems to be a separate feature and as such requires a separate explanation for why it's being added - yes, to make Rando an actual functor, but why?).

**Comment by Nudelsieb** [comment]
@mmrwoods I see your angle now ;-). So basically I have to review if we need a map method (if we call it functor or not is a separate problem). What do we try to solve with a map method? That's a really good question. You could also use `values()` (or in our case `numbers()`) to return an array and use the array's map method. That adds a bit more boilerplate for the user of the library but is also more explicit. It boils down in what you believe in. I prefer more abstraction, so directly map on the Instance (functor) rather than the instance's values.

**Comment by Nudelsieb** [comment]
@mmrwoods I've re-committed this, please give feedback. If you're happy, merge it please :). Also, @myabc your opinion on this is appreciated too!

**Comment by mmrwoods** [comment]
@Nudelsieb Thanks, the updated commit messages are really helpful :-)

The tests fail on CI, but that's a separate issue. I think this should be merged.

**Comment by Nudelsieb** [comment]
@mmrwoods thanks 👍 . Please go ahead and merge it, maybe approve the review first :). Ask @myabc if it is acceptable.

**Pull request merged**
