### PR TITLE
Switch to Yarn for managing dependencies

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by Nudelsieb** [comment]
@myabc I believe you removed the wront file ;-). It should have been `package-lock.json`, not `package.json`.

**Comment by myabc** [comment]
@Nudelsieb duh! 🙄

**Comment by Nudelsieb** [comment]
Can be merge if @mmrwoods is okay with it.

**Comment by mmrwoods** [comment]
@Nudelsieb @myabc I'm cool with using yarn, npm was just simpler for me to start with. Go for it :-)

**Pull request merged**
