### PR TITLE
Prepare for deployment on npm

### PR DESCRIPTION
**Pull request by Nudelsieb**
Re-opened because branch re-named. Original PR here: #8

### CODE REVIEW

**Comment by Nudelsieb** [comment]
@mmrwoods, I followed your suggestions. This should be ready to merge.

**Comment by mmrwoods** [comment]
@Nudelsieb looks good, but don't really understand the point of referencing the individual commits that were squashed, the squashed commit message seems to have everything that those individual commits have (and if there's anything important that isn't included in the squashed commit message, then I'd say the squashed commit message should be updated to include that info, rather than reference other commits).

**Comment by Nudelsieb** [comment]
@mmrwoods, fixed.

**Comment by mmrwoods** [comment]
@Nudelsieb thanks, merged :-)

**Pull request merged**
